language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: '10'
install: npm install
script: npm run validate
after_success:
  - npx codecov
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && npx semantic-release
branches:
  only:
    - develop
    - master
